### ISSUE TITLE
`drizzle-kit push` fails with "PostgresError: column "provider_id" is in  a primary key"

### ISSUE THREAD

**Issue by nickreynolds** [dotnize/tanstarter#4]
I cloned this repo and successfully got it running. The `drizzle-kit push` command works the first time and my DB looks good.

However, if I add anything to the DB schema (adding a new table, not modifying existing ones at all), `drizzle-kit push` fails with this error:

```
[✓] Pulling schema from database...       
PostgresError: column "provider_id" is in 
a primary key
```

This seems related to this drizzle-kit issue: https://github.com/drizzle-team/drizzle-orm/issues/2626

I was able to get around the issue once by adding a name to the primaryKey, but then it fails again on subsequent changes.

**Comment by dotnize** [comment]
The fix for me was adding `.notNull()` to both PKs.

https://github.com/dotnize/tanstarter/commit/61b9654e998628ff82e5d039c47f0c06b2337bb7

```diff
export const oauthAccount = pgTable(
  "oauth_account",
  {
-   provider_id: text(),
-   provider_user_id: text(),
+   provider_id: text().notNull(),
+   provider_user_id: text().notNull(),
    user_id: integer()
      .notNull()
      .references(() => user.id),
  },
  (table) => [primaryKey({ columns: [table.provider_id, table.provider_user_id] })],
);
```

Let me know if that works on your end :)

**Comment by nickreynolds** [comment]
sorry for the late response, but yes this fixed the issue for me, thanks
